export const buildArticleInfo = ({
  title,
  slug,
  origin,
  categories = [],
  incomingLinks = 0,
  revisionCount = 0,
  firstEdited = null,
  lastEdited = null,
}) => ({
  title,
  slug,
  url: `${origin}/wiki/${slug}/`,
  categories,
  incomingLinks,
  backlinksUrl: `${origin}/wiki/${slug}/backlinks/`,
  backlinksJsonUrl: `${origin}/wiki/${slug}/backlinks.json`,
  citeUrl: `${origin}/wiki/${slug}/cite/`,
  citeJsonUrl: `${origin}/wiki/${slug}/cite.json`,
  bibtexUrl: `${origin}/wiki/${slug}/cite.bib`,
  infoUrl: `${origin}/wiki/${slug}/info/`,
  referencesUrl: `${origin}/wiki/${slug}/references.json`,
  relatedUrl: `${origin}/wiki/${slug}/related.json`,
  revisionCount,
  historyUrl: `${origin}/wiki/${slug}/history/`,
  firstEdited: firstEdited ?? null,
  lastEdited: lastEdited ?? null,
});
