import { execFileSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

const contentDir = path.join(projectRoot, 'src', 'content', 'pages');
const outputDir = path.join(projectRoot, 'public', 'history');

// Revision history must come from the article source repository. The in-repo
// `src/content/pages` directory is generated by sync-articles.js and is
// gitignored, so it has no commit history of its own. Resolve the same article
// source roots that sync-articles.js uses.
const defaultArticlesRoot = path.resolve(projectRoot, '..', 'taopedia-articles');
const articlesRoot = process.env.TAOPEDIA_ARTICLES_DIR
  ? path.resolve(process.env.TAOPEDIA_ARTICLES_DIR)
  : defaultArticlesRoot;
const cacheArticlesRoot = path.join(projectRoot, '.cache', 'taopedia-articles');

// Ensure output directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

function resolveArticlesRepo() {
  for (const root of [articlesRoot, cacheArticlesRoot]) {
    if (fs.existsSync(path.join(root, 'content', 'pages'))) {
      return root;
    }
  }
  return null;
}

function ensureFullHistory(repo) {
  // sync-articles.js clones the source repo with --depth=1, which limits the
  // history to a single commit. Unshallow it (best effort) so revisions are complete.
  try {
    const shallow = execFileSync('git', ['rev-parse', '--is-shallow-repository'], {
      cwd: repo,
      encoding: 'utf-8',
    }).trim();
    if (shallow === 'true') {
      execFileSync('git', ['fetch', '--unshallow'], { cwd: repo, stdio: 'ignore' });
    }
  } catch {
    // Not a git repo, or fetch unavailable — fall back to whatever is present.
  }
}

function getGitHistory(repo, relativeSourcePath) {
  try {
    const logOutput = execFileSync(
      'git',
      ['log', '--follow', '--pretty=format:%H|%an|%ae|%at|%s', '--', relativeSourcePath],
      { cwd: repo, encoding: 'utf-8' }
    );

    if (!logOutput) return [];

    return logOutput.split('\n').map(line => {
      const [sha, authorName, authorEmail, timestamp, message] = line.split('|');
      return {
        sha,
        authorName,
        authorEmail,
        timestamp: parseInt(timestamp, 10),
        date: new Date(parseInt(timestamp, 10) * 1000).toISOString(),
        message,
      };
    });
  } catch (error) {
    console.warn(`No git history for ${relativeSourcePath}:`, error.message);
    return [];
  }
}

function walkDirectory(dir, fileList = []) {
  const files = fs.readdirSync(dir);
  files.forEach(file => {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat.isDirectory()) {
      walkDirectory(filePath, fileList);
    } else if (
      file === 'index.md' ||
      file === 'index.mdx' ||
      file.endsWith('.md') ||
      file.endsWith('.mdx')
    ) {
      fileList.push(filePath);
    }
  });
  return fileList;
}

console.log('Generating article history from Git...');

const articlesRepo = resolveArticlesRepo();
if (!articlesRepo) {
  console.warn(
    'Article source repository not found; writing empty history. ' +
      'Place taopedia-articles next to this repo or set TAOPEDIA_ARTICLES_DIR.'
  );
} else {
  ensureFullHistory(articlesRepo);
}

const markdownFiles = walkDirectory(contentDir);

markdownFiles.forEach(filePath => {
  const relativePath = path.relative(contentDir, filePath);
  const slug = path.dirname(relativePath).replace(/\\/g, '/');

  // The generated article is synced from <articles>/content/pages/<slug>/index.mdx,
  // so query the source repository's history for that path.
  const sourcePath = path.posix.join('content', 'pages', slug, 'index.mdx');
  const history = articlesRepo ? getGitHistory(articlesRepo, sourcePath) : [];

  const historyFile = path.join(outputDir, `${slug}.json`);
  const historyFileDir = path.dirname(historyFile);

  if (!fs.existsSync(historyFileDir)) {
    fs.mkdirSync(historyFileDir, { recursive: true });
  }

  fs.writeFileSync(historyFile, JSON.stringify({ slug, history }, null, 2));
  console.log(`  ✓ ${slug} (${history.length} revisions)`);
});

console.log(`✓ Generated history for ${markdownFiles.length} articles`);
