import type { APIRoute } from 'astro';
import { getCollection } from 'astro:content';
import { getPageSlug, historyForSlug } from '../../../lib/article-history';
import { compareTitles } from '../../../lib/title-sort.js';

// Machine-readable new-pages list at /wiki/special/newpages.json. Lists all
// published articles sorted by creation date (the oldest revision in their
// revision history), newest-created first. This complements
// Special:RecentChanges (which lists every edit to any article) and
// Special:MostLinkedPages (which ranks by inbound-link count): this endpoint
// surfaces NEWLY CREATED articles, not recently edited ones. Programmatic
// consumers include feed aggregators, monitoring dashboards, and cross-wiki
// indexers that need to discover new content as it is published.
//
// The creation date is derived from the final entry in the per-article revision
// history (public/history/<slug>.json, generated by scripts/generate-history.js
// and ordered newest-first), matching the first-revision timestamp that
// Special:NewPages shows on the HTML side. Articles whose history file carries
// no dated entry are excluded from the list rather than listed with a null date.
//
// Article URLs use encodeURIComponent for the slug path segment so the
// endpoint remains safe for external consumers even if future slugs contain
// URL-reserved characters (/, ?, #, %).

export const GET: APIRoute = async ({ site }) => {
  const origin = (site ?? new URL('https://taopedia.org')).origin;
  const pages = await getCollection('pages');

  const newPages: Array<{ slug: string; title: string; created: string }> = [];

  for (const page of pages) {
    const slug = getPageSlug(page);
    const history = historyForSlug(slug);
    // History is ordered newest-first; the last entry is the creation revision.
    const creationEntry = history.length > 0 ? history[history.length - 1] : null;
    if (typeof creationEntry?.date !== 'string' || !creationEntry.date) continue;
    newPages.push({ slug, title: page.data.title, created: creationEntry.date });
  }

  // Sort newest-created first; compareTitles slug tiebreak keeps the output
  // deterministic regardless of import.meta.glob traversal order (numeric
  // subnet slugs such as subnet_9 vs subnet_10 sort correctly).
  newPages.sort((a, b) => {
    if (a.created !== b.created) return a.created < b.created ? 1 : -1;
    return compareTitles(a.slug, b.slug);
  });

  const body = JSON.stringify(
    {
      site: origin,
      count: newPages.length,
      pages: newPages.map((p) => ({
        slug: p.slug,
        title: p.title,
        url: `${origin}/wiki/${encodeURIComponent(p.slug)}/`,
        created: p.created,
      })),
    },
    null,
    2,
  );

  return new Response(body, {
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
    },
  });
};
